export enum MESSAGE_TYPE {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

export enum GRANT_STATUS {
  RECEIVED = 'RECEIVED',
  IN_PROCESS = 'IN_PROCESS',
  REJECT = 'REJECT',
  PUBLISH = 'PUBLISH',
}

export enum FILE_TYPE {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  FILE = 'FILE',
}

export enum USER_TYPE {
  ADMIN = 'ADMIN',
  USER = 'USER',
  ANONYMOUS = 'ANONYMOUS',
}

export enum PERMISSIONS {
  USER_VIEW = 'USER_VIEW',
  USER_EDIT = 'USER_EDIT',
  USER_REMOVE = 'USER_REMOVE',

  ORGANIZATION_VIEW = 'ORGANIZATION_VIEW',
  ORGANIZATION_EDIT = 'ORGANIZATION_EDIT',

  TRANSLATION_VIEW = 'TRANSLATION_VIEW',
  TRANSLATION_EDIT = 'TRANSLATION_EDIT',
  TRANSLATION_REMOVE = 'TRANSLATION_REMOVE',

  SOATO_VIEW = 'SOATO_VIEW',
}
